### ISSUE TITLE
An example of how to use it

### ISSUE THREAD

**Issue by championswimmer** [henrixapp/vuex-orbit#1]
i am trying to create a vue app that is connected to a jsonapi endpoint.

I think this would be really helpful for me

**Comment by henrixapp** [comment]
A rather complex example is aviable here: https://github.com/FachschaftMathPhys/tobias/tree/master/client

Take a look at the schema definition, which works like orbitjs:
https://github.com/FachschaftMathPhys/tobias/blob/master/client/store/schema.ts

and the setup of buckets etc:
https://github.com/FachschaftMathPhys/tobias/blob/master/client/store/api.ts

then you can define a Vuex.Store (I recommend looking at the generated state in vue dev tools for chrome)

https://github.com/FachschaftMathPhys/tobias/blob/master/client/store/index.ts

I will publish a minimal viable example, if you wish to.

**Comment by henrixapp** [comment]
[![Edit Vuex-orbit example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/r4l8ml75rp) which queries against an instance of  https://github.com/henrixapp/petkeeper-server

**Comment by championswimmer** [comment]
Thanks a lot!!
